baseurl = "brodie.cookwithchef.com/"
languageCode = "en-us"
theme = "brodietime"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "pink"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 0
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true

[languages]
  [languages.en]
    title = "Brodie Blog"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
